### ISSUE TITLE
1st Code Review (Koodikatselmointi)

### ISSUE THREAD

**Issue by AaaDee** [nigoshh/hoax#1]
*Seeing that all of your documentation is in English, I have written the feedback in English as well. If you'd prefer a version in Finnish, please contact me via GitHub or through the course instructors*

HOAX Booking Review

Downloaded 8.10. 16.40

Looking good! Based on my testing, the databases and all main functionality seem to be working great! Hence my comments will be nitpicking on small stuff that should be easy to fix before the final deadline

Validation: Most of the stuff seem to be working as expected! However, I was able to enter a super long community name and a negative price for a resource.

Grammar stuff: Note that in English it is common to use capital letters when starting the names of tabs, database columns etc, which should be easy to fix. Also note in readme.md that the past tense of "pay" is "paid", not "payed"

General looks and UI: At the moment the site looks pretty much written on the terms of the databases, so it would be nice to see at least a few fixes before the final deadline:
    - In the databases the details- edit- and delete- links are displayed as a part of the table. It would be nice to have these as separate buttons.
    - In the Resources-tab there is a "Numbers"-colum. I'm not sure what this means, so perhaps it could be a good idea to clarify it?
    - On the Bookings-tab you still have start_date and end_date which isn't too elegant with the underscores
    - On Bookings i'm also sure whether you need the Account-field since presumably you are always booking stuff as the user who has logged in.
    - In pages for individual user, you have the column names "Value" and "Attribute", which you could (and in my opinion should) drop off.

For the name "Resources", I think you might be looking for the word "Facilities", but your call.

In the subfolders (auth, account etc.) you have empty and unused __init.py__ -files. It would be nice to get rid of them, unless there's some use for them I'm not aware of.

For readablity, it would be nice to have some comments here and there. Database definitions and forms I can live with, but for example it would be nice to know what the methods in the utils-file are used for.

In the database diagram, you have included the invoice-table which at the moment is not utilised. I assume this feature will be implemented soon but if not, remember to update the diagram!

And like I said, things are looking really good and I'm sure that you'll be managing really well with this course. Keep up the good work! -A

**Comment by nigoshh** [comment]
yo thanks for the insight! and good luck with the course, too
